### ISSUE TITLE
Fechar aba após o envio da mensagem

### ISSUE THREAD

**Issue by daniloffernandes** [RobeMatias/ws_treinamento#1]
Robenilson, favor verificar pois ao enviar a mensagem, o RPA não fecha a aba, apenas vai abrindo cada vez mais abas.
Recomendo que verifique a possibilidade de adicionar um trecho no final do código de envio.
Sugestão:
1 - Se for Windows o comando deve ser pyautogui.hotkey('ctrl'+'f4'), onde ele vai fechar apenas 1 aba.
2 - Se for Linux o comando deve ser pyautogui.hotkey('ctrl'+w'), onde ele vai fechar apenas 1 aba.

É importante ter pelo uma aba aberta antes de iniciar a execução.

**Comment by RobeMatias** [comment]
Olá !
Foram feito as correções necessárias, para o fechamento da guia após o envio.
