### ISSUE TITLE
Janela sempre na frente

### ISSUE THREAD

**Issue by daniloffernandes** [RobeMatias/ws_treinamento#2]
Olá, bom dia!
Robenilson, poderia verificar a possibilidade do programa ficar com a tela sempre na frente, mesmo quando eu clicar em outro programa?

**Comment by RobeMatias** [comment]
Olá, Boa tarde"
Foi atribuído uma linha de comando,  esta linha configura a janela para que ela esteja sempre no topo de outras janelas.  a janela, Esta linha configura a janela para que ela esteja sempre no topo e acrescentada o parâmetro "grab_anywhere=True" permite que você arraste a janela para qualquer lugar na tela, em vez de estar restrito a um local específico.
