### ISSUE TITLE
Executável do RPA

### ISSUE THREAD

**Issue by daniloffernandes** [RobeMatias/ws_treinamento#3]
Olá, bom dia!
Robenilson, preciso de um executável desse programa, as vezes é complicado pedir que o usuário execute de forma manual  abrindo o VSCODE e terminal ou CMD.

**Comment by RobeMatias** [comment]
Foi deito o desenvolvimento do executavel, utilizando o pyinstaller  o código se disponibilizado no proximo push, o arquivo executavel sera enviado no whatsapp da empresa
